events {}

http {
    upstream taskflow_backend {
        # Default algorithm Round Robin (Lesson 3.2) — this is what you get if nothing is specified

        server backend1:3000;
        server backend2:3000;
        server backend3:3000;

        # For experiments — uncomment the lines below and see:
        # least_conn;   # Least Connections algorithm
        # ip_hash;      # Session Affinity (IP Hash)
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://taskflow_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health {
            proxy_pass http://taskflow_backend;
        }
    }
}
